name: { { name.snakeCase() } }
description: { { { description } } }
version: 0.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  dio: ^5.2.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  {{#hooks}}
  flutter_hooks: ^0.18.6
  {{/hooks}}
  flutter_localizations:
    sdk: flutter
  flutter_use: ^0.0.3
  {{#freezed}}
  freezed_annotation: ^2.2.0
  {{/freezed}}
  google_fonts: ^5.1.0
  go_router: ^10.1.2
  {{#hooks}}
  hooks_riverpod: ^2.3.6
  {{/hooks}}
  {{^hooks}}
  flutter_riverpod: ^2.3.6
  {{/hooks}}
  intl: ^0.18.1
  {{#freezed}}
  json_annotation: ^4.8.1
  {{/freezed}}
  logging: ^1.1.1
  package_info_plus: ^4.0.1
  pretty_dio_logger: ^1.3.1
  {{#codegen}}
  riverpod_annotation: ^2.1.1
  {{/codegen}}
  stack_trace: ^1.11.0

dev_dependencies:
  {{#anyCodegen}}
  build_runner: ^2.4.4
  {{/anyCodegen}}
  custom_lint: ^0.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  {{#freezed}}
  freezed: ^2.3.4
  {{/freezed}}
  {{#anyCodegen}}
  go_router_builder: ^2.0.1
  {{/anyCodegen}}
  http_mock_adapter: ^0.4.4
  {{#freezed}}
  json_serializable: ^6.7.0
  {{/freezed}}
  mocktail: ^1.0.0
  {{#codegen}}
  riverpod_generator: ^2.2.3
  {{/codegen}}
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
